name: Deploy API

on:
  push:
    paths:
      - "Api/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy API to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/todo-dotnet/repo
            git pull

            cd Api
            dotnet publish -c Release -o /var/www/todo-dotnet/publish

            sudo systemctl restart todo-dotnet-api
